### ISSUE TITLE
Interação com JS

### ISSUE THREAD

**Issue by victor-castro** [chaordic/frontend-intern-challenge#1]
A interação com o javascript no "ENCURTAR", é para, de fato encurtar o link ou é apenas para consumir o arquivo JSON, sendo então um encurtador de  link "fake"?

**Comment by brunoventura** [comment]
@victor-castro a ideia é ser um encurtador de link "fake" mesmo, não é necessário de fato encurtar a URL.

**Comment by victor-castro** [comment]
Perfeito, Entendido!
