### ISSUE TITLE
gif Shortener-interaction

### ISSUE THREAD

**Issue by williamthewill** [chaordic/frontend-intern-challenge#13]
O gif Shortener-interaction é apenas para esclarecer o funcionamento do encurtador de link ou faz parte do layout?

**Comment by brunoventura** [comment]
@williamthewill a interação com o botão é um dos diferenciais:
https://github.com/chaordic/frontend-intern-challenge/blob/master/readme.md#diferenciais

Caso opte por não criá-lo, o layout deverá ser criado como o descrito em:
https://github.com/chaordic/frontend-intern-challenge/blob/master/Layout/Preview.jpg

Podemos fechar essa issue ou ficou mais alguma dúvida? :smile:

**Comment by williamthewill** [comment]
Sem mais dúvidas, obrigado ;)
