### ISSUE TITLE
Cor do Guideline difere da do Layout 

### ISSUE THREAD

**Issue by eh-am** [chaordic/frontend-intern-challenge#2]
Por exemplo, o guideline indica que o vermelho utilizado é #AA1423, mas ao abrir o layout no Photoshop verifica-se que a cor utilizada é na verdade #AA1b32

Na prática não influencia muito, eu sei, mas como bons programadores gostamos de consistência :P

**Comment by danilowzn** [comment]
@eh-am boa observação. Tinha algumas layers com as cores erradas, que já foi corrigido.

=]
