### ISSUE TITLE
Uso de bibliotecas/frameworks

### ISSUE THREAD

**Issue by chittolina** [chaordic/frontend-intern-challenge#44]
Boa noite!
O uso de bibliotecas/frameworks neste desafio, é incentivado? Em um dos campos da descrição do desafio é citado que o uso ou não de bibliotecas será avaliado, mas, de que maneira? Digo, desenvolver o layout responsivo e os efeitos sem bibliotecas, são pontos positivos, visto que o desafiado consegue 'se virar' sem bibliotecas, ou negativos, pelo fato de que o desafiado possivelmente não tem experiência com bibliotecas? Gostaria de esclarecer esta dúvida!

Obrigado.

**Comment by diogomoretti** [comment]
Aí que tá o ponto. Justamente essa análise, baseado no tamanho do projeto, que vamos avaliar. Não somos a favor nem contra o uso... e o que vamos avaliar é se foi bom usar ou não!

**Comment by chittolina** [comment]
Certo.
