### ISSUE TITLE
Solicitação de uso

### ISSUE THREAD

**Issue by biliboss** [chaordic/frontend-intern-challenge#9]
Olá, vocês efetuaram um excelente trabalho com a criação deste desafio. A empresa está de parabéns por incentivar tal produção.

Não tenho dúvidas de que este desafio comprove a capacidade de um front-end, por isso gostaria de customiza-ló e utiliza-lo, tudo bem por vocês?

Conhecendo a correria do dia-a-dia, agradeço desde de já a atenção.

**Comment by diogomoretti** [comment]
@biliboss, obrigado pelo elogio, realmente esse teste está bem legal =]

Bom, esse teste nós contruímos baseado [neste teste da Conta Azul](https://github.com/ContaAzul/intern-challenge). Como você pode perceber, nós mudamos bastante coisa, como **layout**, **instruções** e **requisitos**.

Você pode se basear neste teste sem problemas (afinal, é open-source)... mas aconselho adaptá-lo as necessidades da sua empresa :wink:

Abraços!
