### ISSUE TITLE
Branch

### ISSUE THREAD

**Issue by MPorto1994** [chaordic/frontend-intern-challenge#95]
Oi, eu não estou conseguindo fazer um branch. A opção de criar um novo branch não aparece pra mim. Quando me enviaram o email propondo o desafio tinham comentado em aumentar o prazo, então eu respondi e disse que sim, já que era um desafio trabalhoso. Contudo não recebi resposta. Talvez esse seja o motivo do problema, não sei.

**Comment by iurykrieger** [comment]
Olá @MPorto1994,

para criar uma branch, primeiro você precisa fazer um [fork](https://help.github.com/en/articles/fork-a-repo) do repositório como está na descrição do `README.md`. Após o fork, o repositório é seu, você vai poder fazer uma branch sua de desenvolvimento local, onde você colocará seus commits.

Quando quiser submeter o seu fork, você pode abrir um [pull request](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork) lá no **seu** repositório do desafio, apontando para fazer o merge no [repositório](https://github.com/iurykrieger/frontend-developer-challenge) que você fez o fork.

Espero que tenha respondido a sua dúvida :smile:

**Comment by MPorto1994** [comment]
Obrigado, resolveu sim! Já enviei o meu, aguardo um retorno.
